CREATE TABLE IF NOT EXISTS balances (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  available NUMERIC(18,2) NOT NULL DEFAULT 0,
  pending NUMERIC(18,2) NOT NULL DEFAULT 0,
  total_earned NUMERIC(18,2) NOT NULL DEFAULT 0,
  this_month NUMERIC(18,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
